services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: diary4
      MYSQL_DATABASE: diary4
      MYSQL_USER: diary4
      MYSQL_PASSWORD: diary4
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pdiary4"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://diary4:diary4@mysql:3306/diary4
      - CLERK_SECRET_KEY=your_clerk_secret_key
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: